# Generated by Django 4.0.4 on 2023-07-19 17:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('next_run', models.DateTimeField(auto_now=True, verbose_name='Дата следующей рассылки')),
                ('interval', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=30, verbose_name='Периодичность')),
                ('status_sending', models.CharField(choices=[('Завершена', 'завершена'), ('Создана', 'создана'), ('Запущена', 'активирована')], max_length=30, verbose_name='Статус')),
                ('start_sending_date', models.DateField(default=datetime.datetime(2023, 7, 19, 20, 44, 18, 319873), verbose_name='Дата начала')),
                ('start_sending_time', models.TimeField(blank=True, default=datetime.time(20, 44, 18, 319872), null=True, verbose_name='время рассылки')),
                ('customer', models.ManyToManyField(to='customer.customer', verbose_name='Клиент')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sending.message', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('can_view_sending', 'Can view sending'), ('can_disable_sending', 'Can disable sending')],
            },
        ),
    ]
